### ISSUE TITLE
Invalid external image URL

### ISSUE THREAD

**Issue by yagiz-dev** [CYGOnetwork/lf-applet#1]
I saw this in your code (line 21) :
`<img src="http://cygonetwork.cf/go/ow_userfiles/themes/theme_image_1.png" alt="" width="37" height="37" />`

Image URL seems to be unreachable in my end, please check that.

(I'm bored and just zapping in my GitHub feed lol)

**Comment by humbletyrant** [comment]
Yep, I pulled it directly from the old site. It's fixed now!
